/**
 * Load pre-bundled heavy extensions (permission / subagents / mcp) as
 * InlineExtension factories — no jiti, no TypeScript transpile at session start.
 *
 * Bundles live at: node_modules/<pkg>/.pi-web-bundle/extension.mjs
 * Generated by: scripts/bundle-builtin-extensions.mjs
 */
import { existsSync, readFileSync } from "fs";
import { createRequire } from "module";
import { dirname, join } from "path";
import { pathToFileURL } from "url";
import type { ExtensionFactory, InlineExtension } from "@earendil-works/pi-coding-agent";

const require = createRequire(import.meta.url);

export const HEAVY_EXTENSION_SPECS = [
  {
    name: "permission",
    packageName: "@gotgenes/pi-permission-system",
  },
  {
    name: "subagents",
    packageName: "@gotgenes/pi-subagents",
  },
  {
    name: "mcp-adapter",
    packageName: "pi-mcp-adapter",
  },
] as const;

export type HeavyLoadResult = {
  factories: InlineExtension[];
  notes: string[];
  missing: string[];
};

function resolvePackageRoot(packageName: string): string | null {
  const parts = packageName.split("/");
  const candidates: string[] = [join(process.cwd(), "node_modules", ...parts)];
  try {
    for (const base of require.resolve.paths(packageName) ?? []) {
      candidates.push(join(base, ...parts));
    }
  } catch {
    // ignore
  }
  try {
    candidates.push(dirname(require.resolve(`${packageName}/package.json`)));
  } catch {
    // exports may block package.json
  }
  for (const root of candidates) {
    if (!root || !existsSync(join(root, "package.json"))) continue;
    try {
      const name = (JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { name?: string }).name;
      if (name === packageName) return root;
    } catch {
      // ignore
    }
  }
  return null;
}

export function resolveHeavyBundlePath(packageName: string): string | null {
  const root = resolvePackageRoot(packageName);
  if (!root) return null;
  const bundle = join(root, ".pi-web-bundle", "extension.mjs");
  return existsSync(bundle) ? bundle : null;
}

let cached: Promise<HeavyLoadResult> | null = null;

/**
 * Import prebundled default exports once per process.
 * If a bundle is missing, it is listed in `missing` (caller may fall back to TS paths).
 */
export function loadHeavyExtensionFactories(): Promise<HeavyLoadResult> {
  if (cached) return cached;
  cached = (async (): Promise<HeavyLoadResult> => {
    const factories: InlineExtension[] = [];
    const notes: string[] = [];
    const missing: string[] = [];

    for (const spec of HEAVY_EXTENSION_SPECS) {
      const bundle = resolveHeavyBundlePath(spec.packageName);
      if (!bundle) {
        missing.push(spec.packageName);
        notes.push(`Heavy bundle missing for ${spec.packageName} (run npm run bundle:extensions)`);
        continue;
      }
      try {
        const mod = (await import(pathToFileURL(bundle).href)) as { default?: ExtensionFactory };
        const factory = mod.default;
        if (typeof factory !== "function") {
          notes.push(`Heavy bundle ${spec.name} has no default factory export`);
          missing.push(spec.packageName);
          continue;
        }
        factories.push({ name: spec.name, factory });
        notes.push(`Heavy factory loaded: ${spec.name}`);
      } catch (e) {
        missing.push(spec.packageName);
        notes.push(
          `Heavy factory import failed ${spec.name}: ${e instanceof Error ? e.message : String(e)}`,
        );
      }
    }

    return { factories, notes, missing };
  })();
  return cached;
}

/** Force re-import (tests / after rebundle in same process). */
export function invalidateHeavyExtensionFactories(): void {
  cached = null;
}
